# Generated by Django 5.2.5 on 2025-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBase',
            fields=[
                ('account_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('working_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimate_ben', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_type', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('report_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Base',
                'verbose_name_plural': 'Account Base Records',
                'db_table': 'account_base',
                'managed': False,
            },
        ),
    ]
